version: "2.24.5"
services:
      postgres:
        image: postgres:16.1-alpine
        environment:
          - POSTGRES_USER=root
          - POSTGRES_PASSWORD=secret
          - POSTGRES_DB=bank
        healthcheck:
          test: [ "CMD-SHELL", "pg_isready -d bank" ]
          interval: 5s
          timeout: 5s
          retries: 5
      api:
        build:
          context: .
          dockerfile: Dockerfile
        ports:
          - "8080:8080"
        environment:
          - DB_SOURCE=postgresql://root:secret@postgres:5432/bank?sslmode=disable
        depends_on:
          postgres:
            condition: service_healthy