version: "2.24.5"
services:
      postgres:
        image: postgres:16.1-alpine
        environment:
          - POSTGRES_USER=root
          - POSTGRES_PASSWORD=secret
          - POSTGRES_DB=bank
        ports:
          - "5432:5432"
        volumes:
          - data-volume:/var/lib/postgresql/data
        redis:
          image: redis:7.2.4-alpine
        healthcheck:
          test: [ "CMD-SHELL", "pg_isready -d bank" ]
          interval: 5s
          timeout: 5s
          retries: 5
      api:
        build:
          context: .
          dockerfile: Dockerfile
        ports:
          - "8080:8080"
          - "9090:9090"
        environment:
          - DB_SOURCE=postgresql://root:secret@postgres:5432/bank?sslmode=disable
          - REDIS_ADDRESS=redis:6379
        depends_on:
          - postgres
          - redis
        entrypoint:
          [
            "/app/wait-for.sh",
            "postgres:5432",
            "--",
            "/app/start.sh"
          ]
        command: [ "/app/main" ]
      volumes:
        data-volume:
